services:
  - type: web
    name: doudizhu-game-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node scripts/init-postgres.js; npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.xovzplyeneqbgfymronn:%40Aaa92818137@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres